### PR TITLE
links to documentation / more build commands in README.md

### PR DESCRIPTION
**Pull request by okybaca**
in the top menu, links to FAQ and wiki (legacy) were added. forum link was removed from help submenu as 'forum' is in already in the top menu. "About this page" and "Javascript info" were moved to bottom of help submenu, since they are not the most important ones.
in README.md command to build yacy was added into Compiling YaCy section

### CODE REVIEW

**Comment by Orbiter** [comment]
The Readme changes are good but I would prefer to let the top menu in the way it was

**Comment by okybaca** [comment]
> The Readme changes are good but I would prefer to let the top menu in the way it was

ok. 
btw, why?

can you merge it partialy, or what to do now?

**Comment by thkoch2001** [comment]
Hi okybaca,

thank you for contributing! To make this easier, I cherry-picked the commit "link to english wiki" from this pull request.

I'm also skeptic about the other commits:

- It seems more verbose than necessary.
- The change to the template also removes links and there is no explanation in the commit message why this can be removed.
- There are two merge commits in the pull request. Please rebase pull requests so that the git history remains as understandable as possible.

I'm sure there are many articles on best practices for pull requests out there. Let me know if you see one that is good.

**Comment by Orbiter** [comment]
Please make a pull request with the readme update only

**Pull request closed without merging**
